
apiVersion: batch/v1
kind: Job
metadata:
  name: never-ending-job
spec:
  template:
    spec:
      containers:
      - name: infinite-loop
        image: quay.io/app-sre/debug-container
        command: ["sh", "-c", "while true; do sleep 30; done"]
      restartPolicy: Never
  backoffLimit: 0

